--- #YAML:1.0
name:                Crypt-IDA
version:             0.01
abstract:            Michael Rabin's Information Dispersal Algorithm
license:             ~
author:              
    - Declan Malone <idablack@sourceforge.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Math::FastGF2:                 0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
